version: "3.7"

services:
  blahblah_frontend:
    container_name: blahblah_frontend
    build:
      context: ./frontend/blahblah/
      dockerfile: dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  blahblah_webserver:
    container_name: blahblah_webserver
    build:
      context: ./backend/WebServer/
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net
    volumes:
      - /var/blahblah/attachments/img:/var/blahblah/attachments/img

  blahblah_api_gateway:
    container_name: blahblah_api_gateway
    build:
      context: ./backend/gateway/
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  blahblah_rtc_server:
    container_name: blahblah_rtc_server
    build:
      context: ./backend/RTCServer/
      dockerfile: dockerfile
    ports:
      - "33332:33332"
    stdin_open: true
    tty: true
    networks:
      - default
      - blahblah_net

  envoy:
    image: envoyproxy/envoy-dev
    ports:
      - "80:80"
      - "443:443"
      - "9901:9901"
    environment:
      ENVOY_UID: 0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/live/blahblah.movebxeax.me/privkey.pem:/etc/letsencrypt/live/blahblah.movebxeax.me/privkey.pem
      - /etc/letsencrypt/live/blahblah.movebxeax.me/fullchain.pem:/etc/letsencrypt/live/blahblah.movebxeax.me/fullchain.pem
      - /etc/letsencrypt/live/ov.blahblah.movebxeax.me/privkey.pem:/etc/letsencrypt/live/ov.blahblah.movebxeax.me/privkey.pem
      - /etc/letsencrypt/live/ov.blahblah.movebxeax.me/fullchain.pem:/etc/letsencrypt/live/ov.blahblah.movebxeax.me/fullchain.pem

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes",  "--replica-read-only", "no",  "--requirepass", "***********"]
    ports:
      - "6379:6379"
    networks:
      - default
      - blahblah_net

  openvidu-server:
    container_name: blahblah-openvidu-server
    build:
      context: ./openvidu-server
      dockerfile: dockerfile
    restart: on-failure
    network_mode: host
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    ports:
      - "4443:4443"
    volumes:
      - ./coturn:/run/secrets/coturn
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
      - ${OPENVIDU_RECORDING_CUSTOM_LAYOUT}:${OPENVIDU_RECORDING_CUSTOM_LAYOUT}
      - ${OPENVIDU_CDR_PATH}:${OPENVIDU_CDR_PATH}
    env_file:
      - .env
    environment:
      - SERVER_SSL_ENABLED=true
      - SERVER_PORT=4443
      - KMS_URIS=["ws://blahblah.movebxeax.me:8888/kurento"]
      - COTURN_IP=${COTURN_IP:-auto-ipv4}
      - COTURN_PORT=${COTURN_PORT:-3478}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

  kms:
    image: ${KMS_IMAGE:-kurento/kurento-media-server:6.18.0}
    restart: always
    network_mode: host
    ulimits:
      core: -1
    volumes:
      - /opt/openvidu/kms-crashes:/opt/openvidu/kms-crashes
      - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
      - /opt/openvidu/kurento-logs:/opt/openvidu/kurento-logs
    environment:
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=57000
      - GST_DEBUG=${KMS_DOCKER_ENV_GST_DEBUG:-}
      - KURENTO_LOG_FILE_SIZE=${KMS_DOCKER_ENV_KURENTO_LOG_FILE_SIZE:-100}
      - KURENTO_LOGS_PATH=/opt/openvidu/kurento-logs
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  coturn:
    image: openvidu/openvidu-coturn:2.25.0
    restart: on-failure
    ports:
      - "${COTURN_PORT:-3478}:${COTURN_PORT:-3478}/tcp"
      - "${COTURN_PORT:-3478}:${COTURN_PORT:-3478}/udp"
    env_file:
      - .env
    volumes:
      - ./coturn:/run/secrets/coturn
    command:
      - --log-file=stdout
      - --listening-port=${COTURN_PORT:-3478}
      - --fingerprint
      - --min-port=${COTURN_MIN_PORT:-57001}
      - --max-port=${COTURN_MAX_PORT:-65535}
      - --realm=openvidu
      - --verbose
      - --use-auth-secret
      - --static-auth-secret=$${COTURN_SHARED_SECRET_KEY}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

networks:
  blahblah_net:
    driver: bridge