# jwt
# unit is ms. 15 * 24 * 60 * 60 * 1000 = 15days 1296000000
# 60 * 60 * 1000 = 3600000



jwt:
  secret: ***********

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allow-credentials: false
            allowedHeaders: '*'
            allowedMethods: '*'
#      no auth
      routes:
      - id: web-service-no-auth
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/**
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
#     auth
      - id: aubout_me
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/aboutme
          - Method=POST, PUT
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: article
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/articles/**
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: comment
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/comments/**
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: like
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/likes/**
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: notification
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/notifications/**
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: subscribe
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/subscribes/**
          - Method=POST, DELETE
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: user
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/users/me, /web-service/api/users
          - Method=GET, PUT, DELETE
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

      - id: video
        uri: http://172.17.0.1:8081
        predicates:
          - Path=/web-service/api/videos[^/]*(?<!/main)(?<!/hashtag)/**
        filters:
          - RewritePath=/web-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter

#      no auth
      - id: stream-service
        uri: http://172.17.0.1:33332
        predicates:
          - Path=/stream-service/**
        filters:
          - RewritePath=/stream-service/(?<segment>.*), /$\{segment}

#     auth
      - id: stream-service
        uri: http://172.17.0.1:33332
        predicates:
          - Path=/stream-service[^/]*(?<!/rooms)(?<!/onAir)/**
        filters:
          - RewritePath=/stream-service/(?<segment>.*), /$\{segment}
          - JwtAuthenticationFilter